sudo: required
services:
  - docker

before_install:
  - docker build -t jackieni/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jackieni/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker"
  env: "Docker-env-2"
  bucket_name: "elasticbeanstalk-us-west-1-214998001730"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
